---
# tasks file for mysql_db
  - name: Install MySQL database
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
        - mysql-server
        - mysql

  - name: Start MySQL Service
    service:
      name: mysqld
      state: started
      enabled: yes

  - name: Create Application Database
    mysql_db:
      name: "{{ db_name }}"
      state: present

  - name: Create Application User
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_user_password }}"
      priv: '*.*:ALL'
      state: present
      host: '%'